"""empty message

Revision ID: 390d0921b388
Revises: 8daef1caf2a7
Create Date: 2026-07-13 17:41:23.602930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390d0921b388'
down_revision = '8daef1caf2a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_activity_logs', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('can_view_activity_logs')

    # ### end Alembic commands ###
