"""add sku and low stock threshold

Revision ID: c28368093746
Revises: 8122f3b85537
Create Date: 2026-07-10 18:40:00.467869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28368093746'
down_revision = '8122f3b85537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
