"""create stock transactions table

Revision ID: ccbe09dcca7a
Revises: c28368093746
Create Date: 2026-07-13 12:29:21.493827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbe09dcca7a'
down_revision = 'c28368093746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'stoack_transaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('transaction_type', sa.String(length=20), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('previous_stock', sa.Integer(), nullable=False),
        sa.Column('new_stock', sa.Integer(), nullable=False),
        sa.Column('remarks', sa.String(length=255), nullable=True),
        sa.Column('reference_no', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reference_no'),
    )
    with op.batch_alter_table('stoack_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stoack_transaction_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stoack_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['sku'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('stoack_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stoack_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_stoack_transaction_product_id'))

    op.drop_table('stoack_transaction')

    # ### end Alembic commands ###
