"""add stock transaction permissions

Revision ID: df3d24d0164a
Revises: ccbe09dcca7a
Create Date: 2026-07-13 12:39:34.859181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3d24d0164a'
down_revision = 'ccbe09dcca7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_stock_transactions', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_adjust_stock', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('can_adjust_stock')
        batch_op.drop_column('can_view_stock_transactions')

    # ### end Alembic commands ###
